apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argoappapp01-app
spec:
  project: default
  destination: 
    namespace: sandbox
    server: https://kmaster:6443
  source:
    path: argoapp-app01/argofiles
    repoURL: "https://github.com/ak1922/argo-apps.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
