pipeline{
    agent {
        label 'c1'
    }
    options {
         buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '6', numToKeepStr: '10')
    }
    environment{
        dockerhub_cred = credentials('dockerhub_cred')
        DOCKER_IMAGE = "akwasi14/argoapp-app01"
        DOCKER_TAG = "$BUILD_NUMBER"
    }
    stages {
        stage('Git checkout') {
            steps {
                echo '*** checkout code **'
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ak1922/argo-apps.git']])
            }
        }
        stage('Listing files') {
            steps {
                dir('argoapp-app01') {
                echo '*** Listing files ***'
                sh 'ls -ltr'
                }
            }
        }
        stage('Docker build') {
            steps {
                dir('argoapp-app01') {
                    echo '*** Building docker file ***'
                    sh 'docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .'
                }
            }
        }
        stage('Docker push') {
            steps {
                echo '*** Docker tag and push image ***'
                sh 'echo $dockerhub_cred_PSW | docker login -u $dockerhub_cred_USR --password-stdin'
                sh 'docker push ${DOCKER_IMAGE}:${DOCKER_TAG}'
                sh 'docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest'
                sh 'docker push ${DOCKER_IMAGE}:latest'
            }
        }
        stage('Argocd stage') {
            steps {
                dir('argoapp-app01') {
                    echo '*** Creating app ***'
                    sh 'kubectl apply -f argoapp-app01.yaml'
                    sh 'kubectl get all'
                }
            }
        }
    }
}
